apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-stock-app
  template:
    metadata:
      labels:
        app: flask-stock-app
    spec:
      containers:
      - name: flask-stock-app
        image: preethikha9/flask-stock-app
        ports:
        - containerPort: 5000
